name: AI Dependency Management

on:
  schedule:
    - cron: '0 0 * * 1'  # Run weekly on Monday at midnight
  workflow_dispatch:  # Allow manual triggering

jobs:
  dependency-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pip-tools
          
      - name: Check for dependency updates
        id: check-updates
        run: |
          if [ -f requirements.in ]; then
            pip-compile requirements.in --upgrade --output-file requirements.txt.new
            if ! cmp -s requirements.txt requirements.txt.new; then
              echo "updates_available=true" >> $GITHUB_OUTPUT
              mv requirements.txt.new requirements.txt
            else
              echo "updates_available=false" >> $GITHUB_OUTPUT
              rm requirements.txt.new
            fi
          elif [ -f requirements.txt ]; then
            # Create a temporary requirements.in from requirements.txt
            grep -v "^#" requirements.txt | grep -v "^$" > requirements.in.tmp
            pip-compile requirements.in.tmp --upgrade --output-file requirements.txt.new
            if ! cmp -s requirements.txt requirements.txt.new; then
              echo "updates_available=true" >> $GITHUB_OUTPUT
              mv requirements.txt.new requirements.txt
            else
              echo "updates_available=false" >> $GITHUB_OUTPUT
              rm requirements.txt.new
            fi
            rm requirements.in.tmp
          else
            echo "No requirements file found"
            echo "updates_available=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Create Pull Request with AI analysis
        if: steps.check-updates.outputs.updates_available == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "🤖 AI依存関係の自動更新"
          title: "🤖 AI依存関係の自動更新"
          body: |
            # AI依存関係更新レポート 📊
            
            このプルリクエストは、依存関係を最新バージョンに更新するためにAIによって自動的に作成されました。
            
            ## 更新内容
            
            依存関係が最新バージョンに更新されました。これにより、以下のメリットが得られます：
            
            - セキュリティの向上：既知の脆弱性の修正
            - バグ修正：最新のバグ修正の適用
            - 新機能：新しい機能や改善点の利用
            
            ## 推奨アクション
            
            1. このプルリクエストをレビューする
            2. 自動テストが成功することを確認する
            3. 互換性の問題がないことを確認する
            4. 問題がなければマージする
            
            このプルリクエストは、依存関係を最新の状態に保つためのベストプラクティスに従って作成されました。
          branch: ai-dependency-updates
          delete-branch: true
          labels: |
            dependencies
            automated-pr
            ai-generated